name: Clojure CI

on:
  push:
    branches: [ "master", "dev"]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    - name: Setup Clojure
      # You may pin to the exact commit or the version.
      # uses: DeLaGuardo/setup-clojure@05cb4bfdf57855f122e75b71e45224775cdfc4a0
      uses: DeLaGuardo/setup-clojure@9.5
      with:
        cli: latest
        # Set to `true` to fix problems realted to wrongly populated tool cache
        # invalidate-cache: true
    - name: Cache maven project dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-clojure-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-clojure
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7

    - name: Display SemVer
      run: |
        echo "SemVer: $GITVERSION_SEMVER"
    - name: Run CI
      run: clojure -T:build ci
    - uses: actions/upload-artifact@v3
      with:
        name: Artifacts-V3
        path: ~/target/html2hiccup*.jar
